name: Test macOS Binary

on:
  workflow_dispatch:

jobs:
  test-macos-binary:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Make binary executable
        run: chmod +x ./mscp

      - name: Run binary
        run: ./mscp -v

